- name: Hello World Sample
  hosts: localhost
  gather_facts: False

  vars:
    users:
      alice:
        name: Alice Appleworth
        telephone: 123-456-7890
      bob:
        name: Bob Bananarama
        telephone: 987-654-3210
      test1:
        name: Test 1
        telephone: 123-456-7890
      test2:
        name: Test 2
        telephone: 123-456-7890
        
  tasks:
    # with predefined vars
    - name: Print phone records
      debug:
        msg: "User {{ item.key }} is {{ item.value.name }} ({{ item.value.telephone }})"
      loop: "{{ lookup('dict', users) }}"
    
    # with inline dictionary
    - name: show dictionary
      debug:
        msg: "{{item.key}}: {{item.value}}"
      with_dict: {a: 1, b: 2, c: 3}
    
    # Items from loop can be used in when: statements
    - name: set_fact when alice in key
      set_fact:
        alice_exists: true
      loop: "{{ lookup('dict', users) }}"
      when: "'t' in users[name]"
